### ISSUE TITLE
Submodule support

### ISSUE THREAD

**Issue by mattgreen** [mattmc3/reel#2]
First, thanks for this project. I really appreciate the minimalistic approach used here.

One thing to consider is optional support for git submodules (or something similar) for the clone operation. In essence, a pointer to a remote plugin repo that can be updated as the user wishes. The goal is to use reel in an existing dotfiles repo, leveraging reel's strengths of separating out user files from plugin files.

I know not everyone is a fan of submodules (they're pretty bad from a UX perspective) so feel free to close this if it doesn't match your project goals,  but this was the first thing I went looking for.

**Comment by mattmc3** [comment]
@mattgreen - Supporting submodules is definitely in scope for Reel! One of the big reasons I made this is that other plugin mangers (ie: Fisher) don't really use git (they just downloads tar.gz files from GitHub), and Reel's advantage is that it's a thin layer over git that works really well for managing fish plugins. Being a layer over git, it should support things that are common to git repos.

That said, can you tell me what additional support you need though? The `reel in` and `reel clone` command will already recurse submodules: https://github.com/mattmc3/reel/blob/1ac37b9b90f10c22acac1cb41c6a721ea027d520/functions/reel.fish#L68

Also, just to be really forthcoming, I'm still actively developing Reel and have not really advertised it broadly yet. Bugs probably still exist, and I am adding tests using Fishtape to make sure that everything is stable and works well before bringing it out of beta. Any issues you find, I welcome the input (and PRs).

**Comment by mattgreen** [comment]
By submodule support, I was thinking of `git submodule add $git_url`, not `git clone --recursive $git_url`. In other words, the plugin is treated as a submodule within the outer repository. Advantage of this is that the outer dotfiles repo maintains a pointer to the hash that is used instead of toting the files around.

However, this presumes that the context (e.g. dotfiles here) is an existing git repository, which may not always be the case.

I'll keep thinking on this. I don't think it is a blocker to when you want to put reel out there.

**Comment by mattmc3** [comment]
Interesting. So essentially, you're looking for an option to change the mode from `git clone` actions to `git submodule` actions. My original intent was that your plugins directory would just be .gitignored, but this is an interesting use case. My initial thought on this are if you want submodules within your dotfiles, you could easily manage them yourself and then `reel load` those directories, but that would probably mean you want them someplace other than `$__fish_config_dir/plugins`, unless you treated all your plugins like submodules. Reel doesn't really need to talk to git, and this suggestion would leave you with the manual task of updating your submodules yourself. Still, it's worth some additional thought. This might be a nice mode to have, but I also want to be really careful not to put Reel in a position where it's borked someone's dotfiles repo trying to do submodule management. That feels risky.

**Comment by mattgreen** [comment]
Agree. It is out of scope for reel IMO.

Thanks for the discussion. Closing.
