### ISSUE TITLE
New cloning changes clone at the wrong level

### ISSUE THREAD

**Issue by hugoh** [mattmc3/reel#5]
`reel in edc/bass` clones the plugin into `plugins/bass` instead of `plugins/edc/bass'. Here's the output each time it's run:

```
repo: edc/bass
repo: https://github.com/edc/bass
reel: plugin already exists …/.config/fish/plugins/bass
reel: plugin not found …/.config/fish/plugins/edc/bass
```

**Comment by mattmc3** [comment]
Good catch @hugoh. I was toying with moving the plugins up a level, but should not have committed those changes without some more thought/tests and probably a new version number. This has been fixed in the latest commit.
